# nginx.conf
events {
    worker_connections 1024;
}

http {
    # Define o backend para que o Nginx saiba como se conectar
    # O nome 'backend' é o nome do serviço no docker-compose.yml
    upstream nodejs_backend {
        server stagemanager-backend:3000;
    }

    server {
        listen 80;
        server_name localhost;

        # Rota para o Backend (API)
        # Qualquer requisição que comece com /api/ será enviada para o serviço 'backend:3000'
        location /backend/ {
            # O 'alias' (nome do host) é o nome do serviço no docker-compose
            proxy_pass http://nodejs_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Rota para o Frontend (Arquivos Estáticos)
        # Qualquer outra requisição (incluindo '/') servirá o frontend
        location / {
            root /usr/share/nginx/html; # Pasta padrão onde o Nginx espera os arquivos
            index index.html index.htm;
            try_files $uri $uri/ /index.html; # Para Single Page Applications
        }
    }
}